== Caffe2 Installation

=== Set up Anaconda Environment
----
conda create --name py364_caffe2 python=3.6.4
source activate py364_caffe2
----


=== Install Dependencies

Add required system dependencies

.On Mac:
----
brew install \
    automake \
    cmake \
    git \
    glog \
    protobuf
----

.On Ubuntu:
----
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      git \
      libgoogle-glog-dev \
      libgtest-dev \
      libiomp-dev \
      libleveldb-dev \
      liblmdb-dev \
      libopencv-dev \
      libopenmpi-dev \
      libsnappy-dev \
      libprotobuf-dev \
      openmpi-bin \
      openmpi-doc \
      protobuf-compiler
----

Add required Python dependencies:
----
pip install \
    future \
    glog \
    numpy \
    protobuf \
    pydot \
    python-gflags \
    pyyaml \
    scikit-image \
    setuptools \
    six
----

Add optional Python dependencies:
----
conda install --name py364_caffe2 flask graphviz hypothesis jupyter leveldb lmdb matplotlib pydot pyyaml requests scikit-image scipy setuptools tornado zeromq
conda install --name py364_caffe2 -c conda-forge python-nvd3
----


=== Install Caffe2 (Anaconda)

Build from source:
----
git clone --recursive https://github.com/caffe2/caffe2.git
cd caffe2
conda build conda
----

Add Caffe2 to conda list:
----
conda install caffe2 --use-local
----

Add Caffe2 to existing environment:
----
conda install --name py364_caffe2 caffe2 --use-local
----


=== Install Caffe2 (Anaconda Custom)

Download & build Caffe2:
----
git clone --recursive https://github.com/caffe2/caffe2.git
cd caffe2 && mkdir build && cd build
sudo cmake -DUSE_CUDA=OFF -DUSE_LEVELDB=OFF -DCMAKE_PREFIX_PATH=~/anaconda3/envs/py364_caffe2 -DCMAKE_INSTALL_PREFIX=~/anaconda3/envs/py364_caffe2 ..
sudo make install
----

"The flag CMAKE_PREFIX_PATH tells Cmake to look for packages in your conda environment before looking in system install locations (like /usr/local); you almost certainly want to set this flag. CMAKE_INSTALL_PREFIX tells Cmake where to install Caffe2 binaries such as libcaffe2.dylib after Caffe2 has been successfully built; the default is /usr/local.
If you do this, know that Cmake will cache things in this build folder, so you may want to remove it before rebuilding."

When error appears like:
----
/usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4.8: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/workspace_test] Error 1
make[1]: *** [caffe2/CMakeFiles/workspace_test.dir/all] Error 2
make: *** [all] Error 2
----

Please remove libtiff (Refer https://github.com/Russell91/apollocaffe/issues/11):
----
conda remove libtiff
----


=== Verify the Installation

----
cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
----


=== Reference

Official: https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile

Python-nvd3: https://anaconda.org/conda-forge/python-nvd3
